/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vista;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sistemas
 */
public class FrmApartamento extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        TblTorreApartamento = new javax.swing.JTabbedPane();
        TorreApartamento = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        labelTask1 = new org.edisoncor.gui.label.LabelTask();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblApartamento = new javax.swing.JTable();
        dtmTableApartamento = new org.edisoncor.gui.panel.PanelShadow();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblApartamento1 = new javax.swing.JTable();
        panelShadow2 = new org.edisoncor.gui.panel.PanelShadow();
        BtnGrabarCambios1 = new org.edisoncor.gui.button.ButtonAero();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout TorreApartamentoLayout = new javax.swing.GroupLayout(TorreApartamento);
        TorreApartamento.setLayout(TorreApartamentoLayout);
        TorreApartamentoLayout.setHorizontalGroup(
            TorreApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        TorreApartamentoLayout.setVerticalGroup(
            TorreApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        TblTorreApartamento.addTab("PROPIETARIO", TorreApartamento);

        panelImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sistemas\\Pictures\\descarga.jpg")); // NOI18N

        panelImage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sistemas\\Pictures\\ICONNN.jpg")); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        labelTask1.setForeground(new java.awt.Color(0, 0, 0));
        labelTask1.setText("EDIFICIO MULTIFAMILIAR VILLARKADIA II");
        labelTask1.setCategoryFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        labelTask1.setCategorySmallFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        labelTask1.setDescription("    NIT: 809.011.052-5      CALLE 47 A N° 3 - 48 SUR");

        TblApartamento.setBackground(new java.awt.Color(255, 255, 255));
        TblApartamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblApartamento.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        TblApartamento.setForeground(new java.awt.Color(0, 0, 0));
        TblApartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "101", null, "0", "51", "N"},
                {"2", "102", "1", "0", null, "N"},
                {"3", "103", "1", "0", null, "N"},
                {"4", "104", "1", "0", null, "N"},
                {"5", "201", "1", "0", "53", "N"},
                {"6", "202", "1", "0", null, "N"},
                {"7", "203", "1", "0", "1", "N"},
                {"8", "204", "1", "0", null, "N"},
                {"9", "301", "1", "0", "5", "N"},
                {"10", "302", "1", "0", null, "N"},
                {"11", "303", "1", "0", null, "N"},
                {"12", "304", "1", "0", null, "N"},
                {"13", "401", "1", "0", null, "N"},
                {"14", "402", "1", "0", null, "N"},
                {"15", "403", "1", "0", null, "N"},
                {"16", "404", "1", "0", null, "N"},
                {"17", "101", "2", "0", null, "N"},
                {"18", "102", "2", "0", null, "N"},
                {"19", "103", "2", "0", null, "N"},
                {"20", "104", "2", "0", null, "N"}
            },
            new String [] {
                "NUMERO UNICO", "No APARTAMENTO", "No BLOQUE", "MATRICULA", "PARQUEADERO", "ASIGNADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblApartamento.setGridColor(new java.awt.Color(153, 153, 153));
        TblApartamento.setInheritsPopupMenu(true);
        jScrollPane1.setViewportView(TblApartamento);

        dtmTableApartamento.setBackground(new java.awt.Color(0, 0, 0));
        dtmTableApartamento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        TblApartamento1.setBackground(new java.awt.Color(255, 255, 255));
        TblApartamento1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblApartamento1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        TblApartamento1.setForeground(new java.awt.Color(0, 0, 0));
        TblApartamento1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "101", null, "0", "51", "N"},
                {"2", "102", "1", "0", null, "N"},
                {"3", "103", "1", "0", null, "N"},
                {"4", "104", "1", "0", null, "N"},
                {"5", "201", "1", "0", "53", "N"},
                {"6", "202", "1", "0", null, "N"},
                {"7", "203", "1", "0", "1", "N"},
                {"8", "204", "1", "0", null, "N"},
                {"9", "301", "1", "0", "5", "N"},
                {"10", "302", "1", "0", null, "N"},
                {"11", "303", "1", "0", null, "N"},
                {"12", "304", "1", "0", null, "N"},
                {"13", "401", "1", "0", null, "N"},
                {"14", "402", "1", "0", null, "N"},
                {"15", "403", "1", "0", null, "N"},
                {"16", "404", "1", "0", null, "N"},
                {"17", "101", "2", "0", null, "N"},
                {"18", "102", "2", "0", null, "N"},
                {"19", "103", "2", "0", null, "N"},
                {"20", "104", "2", "0", null, "N"}
            },
            new String [] {
                "NUMERO UNICO", "No APARTAMENTO", "No BLOQUE", "MATRICULA", "PARQUEADERO", "ASIGNADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblApartamento1.setGridColor(new java.awt.Color(153, 153, 153));
        TblApartamento1.setInheritsPopupMenu(true);
        jScrollPane2.setViewportView(TblApartamento1);

        javax.swing.GroupLayout dtmTableApartamentoLayout = new javax.swing.GroupLayout(dtmTableApartamento);
        dtmTableApartamento.setLayout(dtmTableApartamentoLayout);
        dtmTableApartamentoLayout.setHorizontalGroup(
            dtmTableApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(dtmTableApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dtmTableApartamentoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        dtmTableApartamentoLayout.setVerticalGroup(
            dtmTableApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
            .addGroup(dtmTableApartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dtmTableApartamentoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        panelShadow2.setBackground(new java.awt.Color(0, 0, 0));
        panelShadow2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        BtnGrabarCambios1.setBackground(new java.awt.Color(204, 204, 204));
        BtnGrabarCambios1.setForeground(new java.awt.Color(0, 0, 0));
        BtnGrabarCambios1.setText("GRABAR CAMBIOS ");

        javax.swing.GroupLayout panelShadow2Layout = new javax.swing.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(BtnGrabarCambios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnGrabarCambios1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtmTableApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(panelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTask1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtmTableApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TblTorreApartamento.addTab("APARTAMENTO", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TblTorreApartamento)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TblTorreApartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAero BtnGrabarCambios1;
    private javax.swing.JTable TblApartamento;
    private javax.swing.JTable TblApartamento1;
    private javax.swing.JTabbedPane TblTorreApartamento;
    private javax.swing.JPanel TorreApartamento;
    private org.edisoncor.gui.panel.PanelShadow dtmTableApartamento;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.label.LabelTask labelTask1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelShadow panelShadow2;
    // End of variables declaration//GEN-END:variables
 
    public org.edisoncor.gui.button.ButtonAero getBtnGrabarCambios1() {
        return BtnGrabarCambios1;
    }

    public void setBtnGrabarCambios1(org.edisoncor.gui.button.ButtonAero BtnGrabarCambios1) {
        this.BtnGrabarCambios1 = BtnGrabarCambios1;
    }

    public javax.swing.JTable getTblApartamento() {
        return TblApartamento;
    }

    public void setTblApartamento(javax.swing.JTable TblApartamento) {
        this.TblApartamento = TblApartamento;
    }

    public javax.swing.JTable getTblApartamento1() {
        return TblApartamento1;
    }

    public void setTblApartamento1(javax.swing.JTable TblApartamento1) {
        this.TblApartamento1 = TblApartamento1;
    }

    public javax.swing.JTabbedPane getTblTorreApartamento() {
        return TblTorreApartamento;
    }

    public void setTblTorreApartamento(javax.swing.JTabbedPane TblTorreApartamento) {
        this.TblTorreApartamento = TblTorreApartamento;
    }

    public javax.swing.JPanel getTorreApartamento() {
        return TorreApartamento;
    }

    public void setTorreApartamento(javax.swing.JPanel TorreApartamento) {
        this.TorreApartamento = TorreApartamento;
    }

    public org.edisoncor.gui.panel.PanelShadow getDtmTableApartamento() {
        return dtmTableApartamento;
    }

    public void setDtmTableApartamento(org.edisoncor.gui.panel.PanelShadow dtmTableApartamento) {
        this.dtmTableApartamento = dtmTableApartamento;
    }

    public javax.swing.JFrame getjFrame1() {
        return jFrame1;
    }

    public void setjFrame1(javax.swing.JFrame jFrame1) {
        this.jFrame1 = jFrame1;
    }

    public javax.swing.JFrame getjFrame2() {
        return jFrame2;
    }

    public void setjFrame2(javax.swing.JFrame jFrame2) {
        this.jFrame2 = jFrame2;
    }

    public javax.swing.JFrame getjFrame3() {
        return jFrame3;
    }

    public void setjFrame3(javax.swing.JFrame jFrame3) {
        this.jFrame3 = jFrame3;
    }

    public javax.swing.JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(javax.swing.JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public javax.swing.JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(javax.swing.JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public javax.swing.JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(javax.swing.JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public javax.swing.JMenu getjMenu4() {
        return jMenu4;
    }

    public void setjMenu4(javax.swing.JMenu jMenu4) {
        this.jMenu4 = jMenu4;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public org.edisoncor.gui.label.LabelTask getLabelTask1() {
        return labelTask1;
    }

    public void setLabelTask1(org.edisoncor.gui.label.LabelTask labelTask1) {
        this.labelTask1 = labelTask1;
    }

    public org.edisoncor.gui.panel.PanelImage getPanelImage1() {
        return panelImage1;
    }

    public void setPanelImage1(org.edisoncor.gui.panel.PanelImage panelImage1) {
        this.panelImage1 = panelImage1;
    }

    public org.edisoncor.gui.panel.PanelImage getPanelImage2() {
        return panelImage2;
    }

    public void setPanelImage2(org.edisoncor.gui.panel.PanelImage panelImage2) {
        this.panelImage2 = panelImage2;
    }

    public org.edisoncor.gui.panel.PanelShadow getPanelShadow2() {
        return panelShadow2;
    }

    public void setPanelShadow2(org.edisoncor.gui.panel.PanelShadow panelShadow2) {
        this.panelShadow2 = panelShadow2;
    }
       public DefaultTableModel getDtmModelTableApartamento(){
        return dtmTableApartamento;
    }
   private void configurarTablaApartamentos() {
        dtmModelTableApartamentos = new javax.swing.table.DefaultTableModel(
            null,
                
            new String[]  {"Numero único", "No. apartamento", "No Bloque",
            "Matricula", "Parqueadero", "Asignado"}
          
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        TblApartamento1.setModel(dtmModelTableApartamentos);    
    }

}
